listen: ':9876'
targets:
  http:
    - name: 'google'
      url: 'https://www.google.com/'
      rps: 0.5 # 2 RPS
      timeout: '1s'
  icmp:
    - name: 'google'
      host: 'www.google.com'
      rps: 0.5 # 2 RPS
      timeout: '1s'
      ttl:   100
    - name: 'digikala'
      host: 'www.digikala.com'
      rps: 0.5 # 2 RPS
      timeout: '1s'

